"""cart

Revision ID: 4b7643354393
Revises: 7c0189ef60f2
Create Date: 2023-08-11 12:36:49.406451

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4b7643354393'
down_revision = '7c0189ef60f2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'category', ['category_slug'])
    op.create_unique_constraint(None, 'product', ['product_slug'])
    op.create_unique_constraint(None, 'tag', ['tag_slug'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tag', type_='unique')
    op.drop_constraint(None, 'product', type_='unique')
    op.drop_constraint(None, 'category', type_='unique')
    # ### end Alembic commands ###
