"""added otp_expires to user

Revision ID: 633ee119e85d
Revises: 9256241d7408
Create Date: 2023-09-23 19:52:10.029895

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '633ee119e85d'
down_revision = '9256241d7408'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('otp_expires', sa.TIMESTAMP(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'otp_expires')
    # ### end Alembic commands ###
