"""bonus-points

Revision ID: 80ef2188cd38
Revises: 96ea2b399bf3
Create Date: 2023-06-23 21:37:57.239183

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '80ef2188cd38'
down_revision = '96ea2b399bf3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('bonus_points', sa.Integer(), nullable=True))
    op.drop_table('user_address')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'bonus_points')
    # ### end Alembic commands ###
