"""added otp to user

Revision ID: 9256241d7408
Revises: 45b8251dd426
Create Date: 2023-09-23 19:26:30.880499

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9256241d7408'
down_revision = '45b8251dd426'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('otp', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'otp')
    # ### end Alembic commands ###
