"""add headings

Revision ID: 94c6d1ea249f
Revises: 633ee119e85d
Create Date: 2023-11-08 17:54:59.223437

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '94c6d1ea249f'
down_revision = '633ee119e85d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('heading',
    sa.Column('visible', sa.Boolean(), nullable=True),
    sa.Column('heading_name', sa.String(length=128), nullable=False),
    sa.Column('heading_slug', sa.String(length=128), nullable=False),
    sa.Column('image_path', sa.String(), nullable=False),
    sa.Column('heading_description', sa.String(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('modified_at', sa.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('heading_slug')
    )
    op.add_column('category', sa.Column('heading_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'category', 'heading', ['heading_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'category', type_='foreignkey')
    op.drop_column('category', 'heading_id')
    op.drop_table('heading')
    # ### end Alembic commands ###
