"""added product measure

Revision ID: 9cf1ed2f8a65
Revises: 795a527eb5eb
Create Date: 2023-09-16 22:44:26.342314

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9cf1ed2f8a65'
down_revision = '795a527eb5eb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('measure', sa.String(), nullable=True))
    op.execute("UPDATE product SET measure = 'gr'")
    op.alter_column('product', 'measure', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product', 'measure')
    # ### end Alembic commands ###
